spring.datasource.url=jdbc:mysql://localhost:3306/workbook?useSSL=false&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true
spring.datasource.username=workusr
spring.datasource.password=workpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver